# docker-compose.yml

version: '2'

services:
  web:
    image: wstevo4891/bolt-network-node
    ports:
      - 80:8080
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db

  db:
    image: postgres
